---
 out_dir: '../p2d_results/run_1/'
 smiles_dir: "./data/pocket-smiles.yaml"
 pocket_dir: "../data/googlenet-dataset/"
 pop_dir: "../data/pops-googlenet/"
 test_split: 0.05
 seed: 666
 features_to_use:
  - 'x'
  - 'y'
  - 'z'
  - 'r'
  - 'theta'
  - 'phi'
  - 'sasa'
  - 'charge'
  - 'hydrophobicity'
  - 'binding_probability'
  - 'sequence_entropy'   
 vocab: "char"
 vocab_path: "./vocab/char_vocab.yaml"

 encoder_config:
  dim: 128 # size of the graph neural network
  num_layers: 6
  num_channels: 3 # number of neural message masking channels form jknmm
  train_eps: True
  num_edge_attr: 1 # number of edge attributes, only chemical bond
  num_features: 11 # has to be consistent with features_to_use
 
 decoder_config:
  # embedding
  # number of tokens + <sos> + <eos> + <pad>
  # char: 48
  num_embeddings: 48 
  embedding_dim: 256

  # rnn
  which_rnn: 'GRU' # 'GRU' or 'LSTM'
  input_size: 256 # size of the recurrent neural network
  hidden_size: 512
  num_layers: 3
  dropout: 0

 batch_size: 256
 num_epoch: 100
 learning_rate: 0.003
 weight_decay: 0.0005